const { google } = require('googleapis');
const { Readable } = require('node:stream');

const DRIVE_SCOPES = ['https://www.googleapis.com/auth/drive.file'];
const INVOICE_EXTENSIONS = /\.(pdf|png|jpe?g)$/i;
const APP_DATA_FILES = new Set(['invoice-format-mappings.json','invoice-records.json','invoice-format-mappings-v2.json','invoice-records-v2.json']);

function getOAuth2Client(redirectUri = process.env.GOOGLE_REDIRECT_URI) {
  const { GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI } = process.env;
  if (!GOOGLE_CLIENT_ID || !GOOGLE_CLIENT_SECRET || !(redirectUri || GOOGLE_REDIRECT_URI)) throw new Error('Google Drive OAuth configuration is incomplete.');
  return new google.auth.OAuth2(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, redirectUri || GOOGLE_REDIRECT_URI);
}
function getAuthorizationUrl(redirectUri) { return getOAuth2Client(redirectUri).generateAuthUrl({ access_type: 'offline', prompt: 'consent', scope: DRIVE_SCOPES }); }
async function exchangeAuthorizationCode(code, redirectUri) { return (await getOAuth2Client(redirectUri).getToken(code)).tokens; }
function getDriveClient() { const client=getOAuth2Client(); if(!process.env.GOOGLE_REFRESH_TOKEN) throw new Error('Google Drive has not been authorized yet.'); client.setCredentials({refresh_token:process.env.GOOGLE_REFRESH_TOKEN}); return google.drive({version:'v3',auth:client}); }
async function listExcelFiles(){const drive=getDriveClient();const response=await drive.files.list({q:"trashed = false and (mimeType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' or mimeType = 'application/vnd.ms-excel')",fields:'files(id,name,mimeType,modifiedTime,size,webViewLink)',orderBy:'modifiedTime desc'});return response.data.files||[];}
async function readExcelFile(fileId){if(!fileId||!/^[a-zA-Z0-9_-]+$/.test(fileId))throw new Error('A valid Google Drive file ID is required.');return(await getDriveClient().files.get({fileId,alt:'media'},{responseType:'arraybuffer'})).data;}
async function uploadInvoice(file){const drive=getDriveClient();const folderId=process.env.GOOGLE_DRIVE_FOLDER_ID;if(!folderId)throw new Error('Google Drive invoice folder is not configured.');return(await drive.files.create({requestBody:{name:file.originalname,mimeType:file.mimetype,parents:[folderId]},media:{mimeType:file.mimetype,body:Readable.from(file.buffer)},fields:'id,name,mimeType,size,webViewLink,parents'})).data;}
async function findAppFile(name){const drive=getDriveClient();const folderId=process.env.GOOGLE_DRIVE_FOLDER_ID;const safe=String(name).replace(/'/g,"\\'");const q=folderId?`trashed = false and name = '${safe}' and mimeType = 'application/json' and '${folderId}' in parents`:`trashed = false and name = '${safe}' and mimeType = 'application/json'`;const response=await drive.files.list({q,fields:'files(id,name,modifiedTime,size,parents)',orderBy:'modifiedTime desc',pageSize:1});return response.data.files?.[0]||null;}
async function readJsonFile(name,fallback=null){const file=await findAppFile(name);if(!file)return fallback;try{const data=await getDriveClient().files.get({fileId:file.id,alt:'media'},{responseType:'text'});return JSON.parse(data.data);}catch(error){if(error?.code===404||error?.response?.status===404)return fallback;throw new Error(`Unable to read ${name}: ${error.message}`);}}
async function writeJsonFile(name,value){const drive=getDriveClient();const folderId=process.env.GOOGLE_DRIVE_FOLDER_ID;if(!folderId)throw new Error('Google Drive invoice folder is not configured.');const existing=await findAppFile(name);const body=JSON.stringify(value,null,2);const media={mimeType:'application/json',body:Readable.from(Buffer.from(body,'utf8'))};if(existing){try{return(await drive.files.update({fileId:existing.id,media,fields:'id,name,modifiedTime,size,webViewLink,parents'})).data}catch(error){if(error?.code!==404&&error?.response?.status!==404)throw error;}}return(await drive.files.create({requestBody:{name,mimeType:'application/json',parents:[folderId]},media,fields:'id,name,modifiedTime,size,webViewLink,parents'})).data;}
async function getDriveFileMetadata(fileId){if(!fileId||!/^[a-zA-Z0-9_-]+$/.test(fileId))return null;try{return(await getDriveClient().files.get({fileId,fields:'id,name,mimeType,size,trashed,parents,webViewLink'})).data}catch(error){if(error?.code===404||error?.response?.status===404)return null;throw error;}}
async function deleteAllInvoiceData(){const drive=getDriveClient();const folderId=process.env.GOOGLE_DRIVE_FOLDER_ID;if(!folderId)throw new Error('Google Drive invoice folder is not configured.');const deleted=[];const skipped=[];
let pageToken;do{const response=await drive.files.list({q:`'${folderId}' in parents and trashed = false`,fields:'nextPageToken,files(id,name,mimeType)',pageToken,pageSize:1000});for(const file of response.data.files||[]){if(INVOICE_EXTENSIONS.test(file.name||'')){try{await drive.files.delete({fileId:file.id});deleted.push(file.name)}catch(error){if(error?.code===404||error?.response?.status===404)skipped.push(`${file.name} (already missing)`);else throw error;}}}pageToken=response.data.nextPageToken;}while(pageToken);
for(const name of APP_DATA_FILES){let token;do{const response=await drive.files.list({q:`trashed = false and name = '${String(name).replace(/'/g,"\\'")}' and mimeType = 'application/json'`,fields:'nextPageToken,files(id,name)',pageToken:token,pageSize:1000});for(const file of response.data.files||[]){try{await drive.files.delete({fileId:file.id});deleted.push(file.name)}catch(error){if(error?.code===404||error?.response?.status===404)skipped.push(`${file.name} (already missing)`);else throw error;}}token=response.data.nextPageToken;}while(token)}
return{deletedCount:deleted.length,deleted,skippedCount:skipped.length,skipped};}
module.exports={DRIVE_SCOPES,exchangeAuthorizationCode,getAuthorizationUrl,listExcelFiles,readExcelFile,uploadInvoice,readJsonFile,writeJsonFile,getDriveFileMetadata,deleteAllInvoiceData};