const zlib=require('node:zlib');
const INVOICE_FIELDS=[{key:'invoiceNumber',label:'Invoice Number',required:true},{key:'invoiceDate',label:'Invoice Date',required:true},{key:'sellerName',label:'Seller Name',required:true},{key:'sellerGSTIN',label:'Seller GSTIN',required:false},{key:'sellerAddress',label:'Seller Address',required:false},{key:'buyerName',label:'Buyer Name',required:true},{key:'buyerGSTIN',label:'Buyer GSTIN',required:false},{key:'buyerAddress',label:'Buyer Address',required:false},{key:'placeOfSupply',label:'Place of Supply',required:false},{key:'taxableAmount',label:'Taxable Amount',required:false},{key:'cgst',label:'CGST',required:false},{key:'sgst',label:'SGST',required:false},{key:'igst',label:'IGST',required:false},{key:'totalTax',label:'Total Tax',required:false},{key:'grandTotal',label:'Grand Total',required:true}];
function clean(v){return String(v??'').replace(/\s+/g,' ').trim()}function normalize(v){return clean(v).toLowerCase().replace(/[^a-z0-9]+/g,'')}
function extractPdfText(buffer){const source=Buffer.from(buffer);const pages=[];const streamRe=/stream\r?\n([\s\S]*?)\r?\nendstream/g;let match;while((match=streamRe.exec(source.toString('latin1')))){let data=Buffer.from(match[1],'latin1');try{data=zlib.inflateSync(data)}catch(_){try{data=zlib.inflateRawSync(data)}catch(_){}}const text=extractPdfOperators(data.toString('latin1'));if(text)pages.push(text)}return pages.length?pages.map((text,i)=>({page:i+1,text:clean(text)})):[{page:1,text:''}]}
function extractPdfOperators(content){const out=[];let m;const literal=/\((?:\\.|[^\\)])*\)\s*Tj/g;while((m=literal.exec(content)))out.push(decodePdfLiteral(m[0].replace(/\)\s*Tj$/,'').replace(/^\(/,'')));const arrays=/\[(.*?)\]\s*TJ/gs;while((m=arrays.exec(content))){const parts=m[1].match(/\((?:\\.|[^\\)])*\)|<[^>]*>/g)||[];out.push(parts.map(p=>p.startsWith('<')?decodePdfHex(p):decodePdfLiteral(p.slice(1,-1))).join(''))}return out.join(' ')}
function decodePdfLiteral(v){return v.replace(/\\n/g,' ').replace(/\\r/g,' ').replace(/\\t/g,' ').replace(/\\([\\()])/g,'$1').replace(/\\[0-7]{1,3}/g,' ')}function decodePdfHex(v){const hex=v.slice(1,-1).replace(/[^0-9a-f]/gi,'');try{return Buffer.from(hex.length%2?`${hex}0`:hex,'hex').toString('utf8')}catch(_){return ''}}
function extractTextPages(file){const mime=String(file.mimetype||'').toLowerCase();if(mime==='application/pdf'||/\.pdf$/i.test(file.originalname))return extractPdfText(file.buffer);return[{page:1,text:''}]}
const RULES={
 invoiceNumber:[/(?:invoice\s*(?:no|number|#)|inv\.?\s*(?:no|number|#)|tax\s*invoice)\s*[:#-]?\s*([A-Z0-9][A-Z0-9./_-]{2,})/i],
 invoiceDate:[/(?:invoice\s*date|date\s*of\s*invoice)\s*[:#-]?\s*(\d{1,2}[/-]\d{1,2}[/-]\d{2,4}|\d{1,2}\s+[A-Za-z]{3,9}\s+\d{2,4})/i],
 sellerGSTIN:[/(?:seller\s*)?(?:gstin|gst\s*(?:no|number))\s*[:#-]?\s*([0-9A-Z]{15})/i],buyerGSTIN:[/(?:buyer\s*)?(?:gstin|gst\s*(?:no|number))\s*[:#-]?\s*([0-9A-Z]{15})/i],
 taxableAmount:[/(?:taxable\s*(?:value|amount)|taxable\s*value)\s*[:#-]?\s*[₹$]?\s*([0-9,]+(?:\.\d{1,2})?)/i],cgst:[/(?:central\s*gst|cgst)\s*[:@#-]?\s*[₹$]?\s*([0-9,]+(?:\.\d{1,2})?)/i],sgst:[/(?:state\s*gst|sgst)\s*[:@#-]?\s*[₹$]?\s*([0-9,]+(?:\.\d{1,2})?)/i],igst:[/(?:integrated\s*gst|igst)\s*[:@#-]?\s*[₹$]?\s*([0-9,]+(?:\.\d{1,2})?)/i],totalTax:[/(?:total\s*(?:tax|gst)|tax\s*total)\s*[:#-]?\s*[₹$]?\s*([0-9,]+(?:\.\d{1,2})?)/i],grandTotal:[/(?:grand\s*total|invoice\s*total|total\s*(?:amount|payable)|net\s*amount)\s*[:#-]?\s*[₹$]?\s*([0-9,]+(?:\.\d{1,2})?)/i],placeOfSupply:[/(?:place\s*of\s*supply|pos)\s*[:#-]?\s*([^\n|]{2,80})/i],sellerName:[/(?:seller|sold\s*by|from)\s*[:#-]?\s*([^\n|]{2,100})/i],buyerName:[/(?:buyer|billed\s*to|bill\s*to|customer)\s*[:#-]?\s*([^\n|]{2,100})/i],sellerAddress:[/(?:seller\s*)?address\s*[:#-]?\s*([^\n|]{5,180})/i],buyerAddress:[/(?:buyer\s*)?address\s*[:#-]?\s*([^\n|]{5,180})/i]};
const LABELS={invoiceNumber:'Invoice No',invoiceDate:'Invoice Date',sellerName:'Seller',sellerGSTIN:'Seller GSTIN',sellerAddress:'Seller Address',buyerName:'Buyer',buyerGSTIN:'Buyer GSTIN',buyerAddress:'Buyer Address',placeOfSupply:'Place of Supply',taxableAmount:'Taxable Amount',cgst:'CGST',sgst:'SGST',igst:'IGST',totalTax:'Total Tax',grandTotal:'Grand Total'};
function firstMatch(text,patterns){for(const p of patterns||[]){const m=text.match(p);if(m?.[1])return clean(m[1])}return ''}
function locateValue(text,label){const source=clean(label);if(!source)return '';const escaped=source.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const m=text.match(new RegExp(`${escaped}\\s*[:#-]?\\s*([^\\n|]{1,180})`,'i'));return m?clean(m[1]):''}
function autoExtract(text,mapping=null){const values={},sources={};for(const field of INVOICE_FIELDS){const saved=mapping?.fields?.[field.key];const savedValue=saved?.sourceLabel?locateValue(text,saved.sourceLabel):'';values[field.key]=savedValue||firstMatch(text,RULES[field.key]||[]);sources[field.key]=saved?.sourceLabel||(values[field.key]?LABELS[field.key]:'')}const lines=text.split(/\n|\r/).map(clean).filter(Boolean);if(!values.sellerName)values.sellerName=lines.find(x=>!/(invoice|tax|gstin|gst|address|date|bill|buyer|customer|amount|total)/i.test(x)&&x.length>2&&x.length<100)||'';if(values.sellerName&&!sources.sellerName)sources.sellerName='Auto detected company line';return{values,sources}}
function findInvoiceNumbers(pages,sourceText){const numbers=[];for(const page of pages){const n=firstMatch(page.text,RULES.invoiceNumber);if(n)numbers.push(n)}if(numbers.length)return[...new Set(numbers)];const fallback=clean(sourceText).match(/\b(?:INV|INVOICE|TAX)[-_/.]?[A-Z0-9/-]{3,}\b/i);return fallback?[fallback[0]]:[]}
function formatFingerprint(text,values){const gst=normalize(values.sellerGSTIN),seller=normalize(values.sellerName);const labels=['invoice','invoice no','invoice number','invoice date','gstin','taxable value','taxable amount','cgst','sgst','igst','grand total','total amount','place of supply','billed to','bill to'];const found=labels.filter(l=>normalize(text).includes(normalize(l))).map(normalize).sort().join('|');if(gst)return`v2|gstin:${gst}|labels:${found}`;if(seller)return`v2|seller:${seller}|labels:${found}`;return`v2|labels:${found}`}
function signatureFromText(text){const p=autoExtract(clean(text),null);return formatFingerprint(text,p.values)}
function classifyInvoice(values){const buyer=normalize(values.buyerName),seller=normalize(values.sellerName),company=normalize('EASY RECHARGE SOLUTION');if(buyer&&buyer.includes(company))return'buy';if(seller&&seller.includes(company))return'sell';return'review'}
function mergeValues(target,source){for(const f of INVOICE_FIELDS)if(!clean(target[f.key])&&clean(source[f.key]))target[f.key]=source[f.key];return target}
function processInvoice(file,mapping=null){const pages=extractTextPages(file),text=pages.map(p=>p.text).join('\n'),probe=autoExtract(text,null),signature=formatFingerprint(text,probe.values),invoiceNumbers=findInvoiceNumbers(pages,text);if(!mapping)return{mode:'mapping-required',signature,pages,invoiceNumbers,values:probe.values,sources:probe.sources,fields:INVOICE_FIELDS,suggestedMapping:{signature,fields:Object.fromEntries(INVOICE_FIELDS.map(f=>[f.key,{label:LABELS[f.key],sourceLabel:probe.sources[f.key]||LABELS[f.key],page:1}]))}};
 const groups=new Map();
 if(invoiceNumbers.length===1){const number=invoiceNumbers[0];let merged={invoiceNumber:number,pages:[]};for(const page of pages){const extracted=autoExtract(page.text,mapping);mergeValues(merged,extracted.values);merged.pages.push(page.page)}groups.set(number,merged)}
 else {let active=null;for(const page of pages){const extracted=autoExtract(page.text,mapping);const explicit=extracted.values.invoiceNumber||invoiceNumbers.find(n=>page.text.includes(n));if(explicit){active=explicit;if(!groups.has(active))groups.set(active,{...extracted.values,pages:[]})}if(!active){active=invoiceNumbers[0]||'UNKNOWN';if(!groups.has(active))groups.set(active,{...extracted.values,pages:[]})}const current=groups.get(active);mergeValues(current,extracted.values);current.pages.push(page.page)}}
 if(!groups.size)groups.set(invoiceNumbers[0]||'UNKNOWN',{...probe.values,pages:pages.map(p=>p.page)});
 const invoices=[...groups.entries()].map(([invoiceNumber,values])=>({...values,invoiceNumber,classification:classifyInvoice(values),sourcePages:[...new Set(values.pages||[])]}));return{mode:'auto',signature,pages,invoices,fields:INVOICE_FIELDS}}
module.exports={INVOICE_FIELDS,clean,normalize,signatureFromText,processInvoice,autoExtract,classifyInvoice,mergeValues,formatFingerprint};